language: c
os: ubuntu
dist: trusty
sudo: require

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - cmake
      - make

before_install:
  - bash linuxPrerequisites.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test