language: c
os: ubuntu
dist: trusty
sudo: require

install: make get-deps

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - cmake
      - make

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - dir