language: c
os: ubuntu

install: make get-deps

compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test