language: c
compiler: gcc

os: linux
dist: bionic
sudo: require

before_script:
  - sudo apt-get install -y gcc cmake make
  - bash linuxPrerequisites.sh
  - mkdir build
  - cd build
  - cmake -DFGG_USE_VULKAN_1_1=ON ..


script:
  - make