version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout:
      -run:
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run: 
          command: 'sudo apt-get install cmake'
      -run:
          command: 'sudo apt-get install g++'
      - run:
          name: 'generating projects'
          command: 'cmake .'
      - run: 
          name: 'building'
          command: 'cmake --build .'
